# Netlify Configuration
# Redirect static assets to CDN

[[redirects]]
  from = "/logos.json"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/logos.json"
  status = 301
  force = true

[[redirects]]
  from = "/logos/*"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/logos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/images/*"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/images/:splat"
  status = 301
  force = true
