# Netlify Configuration

[build]
  command = "npm run build"
  publish = "dist"

# Redirect static assets to CDN

[[redirects]]
  from = "/logos.json"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/public/logos.json"
  status = 301
  force = true

[[redirects]]
  from = "/logos/*"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/public/logos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/images/*"
  to = "https://cdn.jsdelivr.net/gh/PaystackHQ/nigerialogos@master/public/images/:splat"
  status = 301
  force = true
